# Generated by Django 6.0.1 on 2026-01-09 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('renewal', 'Renewal'), ('usage', 'Low Usage'), ('cost', 'Over Budget')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_date', models.DateField(default=django.utils.timezone.now)),
                ('saas_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.saasapp')),
            ],
        ),
    ]
