# Generated by Django 6.0 on 2026-01-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tour',
            name='tours_tour_slug_a32940_idx',
        ),
        migrations.RemoveIndex(
            model_name='tour',
            name='tours_tour_is_acti_e79caf_idx',
        ),
        migrations.RemoveIndex(
            model_name='tour',
            name='tours_tour_price_674fc5_idx',
        ),
    ]
