# Generated by Django 6.0.1 on 2026-02-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('max_people', models.PositiveIntegerField(default=10)),
                ('start_dates', models.JSONField(default=list)),
                ('included_services', models.TextField(help_text='List of included services')),
                ('excluded_services', models.TextField(help_text='List of excluded services')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='destinations.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_gallery', to='media.media')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tours.tour')),
            ],
            options={
                'verbose_name_plural': 'Tour Galleries',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['slug'], name='tours_tour_slug_a32940_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['destination'], name='tours_tour_destina_bbfad1_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_active'], name='tours_tour_is_acti_e79caf_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['price'], name='tours_tour_price_674fc5_idx'),
        ),
    ]
