# Generated by Django 6.0.1 on 2026-02-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=500)),
                ('full_description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_cover', to='media.media')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DestinationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='destinations.destination')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_gallery', to='media.media')),
            ],
            options={
                'verbose_name_plural': 'Destination Galleries',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['slug'], name='destination_slug_528bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['country'], name='destination_country_2ade19_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_featured'], name='destination_is_feat_54f559_idx'),
        ),
    ]
