# Generated by Django 5.2.8 on 2025-11-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(default=1, upload_to='images/partners'),
            preserve_default=False,
        ),
    ]
