# Generated by Django 5.2.8 on 2025-11-11 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_title', models.CharField(max_length=400)),
                ('main_title', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=1000)),
                ('image1', models.ImageField(upload_to='home/images')),
                ('image2', models.ImageField(upload_to='home/images')),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('title', models.CharField(max_length=400)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Program_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.TextField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('number', models.FloatField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.experience')),
            ],
        ),
    ]
