# Generated by Django 6.0 on 2026-01-06 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Business', 'Business'), ('Enterprise', 'Enterprise')], max_length=50)),
                ('licenses', models.PositiveIntegerField()),
                ('assigned_users', models.PositiveIntegerField()),
                ('renewal_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='system.saasapp')),
            ],
        ),
    ]
