# Generated by Django 6.0.1 on 2026-01-08 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qad', models.FloatField()),
                ('shana', models.FloatField()),
                ('zirbaghal', models.FloatField()),
                ('astin_value', models.FloatField()),
                ('astin_type', models.CharField(blank=True, max_length=50, null=True)),
                ('kamar', models.FloatField()),
                ('yakhan_value', models.FloatField()),
                ('yakhan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('shalwar_qad', models.FloatField()),
                ('pacha', models.FloatField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='orders.order')),
            ],
        ),
    ]
