# Generated by Django 6.0.1 on 2026-01-08 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
