# Generated by Django 5.2.8 on 2025-11-11 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/images')),
                ('description', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=400)),
                ('discount', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Trusted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/images')),
                ('link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='home/images')),
                ('featured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.featured')),
            ],
        ),
        migrations.CreateModel(
            name='HeroList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li', models.CharField(max_length=400)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hero')),
            ],
        ),
    ]
