# Generated by Django 5.2.8 on 2025-11-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_experience_achievements_program_services_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature',
            new_name='Featured_list',
        ),
        migrations.RenameModel(
            old_name='HeroList',
            new_name='Hero_List',
        ),
    ]
