# Generated by Django 5.2.8 on 2025-11-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_feature_featured_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='description',
            field=models.TextField(),
        ),
    ]
