# Generated by Django 5.2.8 on 2025-11-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='discraption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='tital',
            new_name='title',
        ),
    ]
