# Generated by Django 6.0 on 2026-01-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('HR', 'HR'), ('Engineering', 'Engineering'), ('Design', 'Design'), ('Finance', 'Finance')], max_length=50)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_items', to='system.saasapp')),
            ],
        ),
    ]
