# Generated by Django 6.0 on 2025-12-29 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_months', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feeplan')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_on', models.DateField(auto_now_add=True)),
                ('method', models.CharField(max_length=50)),
                ('player_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.playerfee')),
            ],
        ),
    ]
