# Generated by Django 6.0.1 on 2026-01-09 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaaSApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('license_count', models.PositiveIntegerField()),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('renewal_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_users', models.ManyToManyField(blank=True, to='accounts.user')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.department')),
            ],
        ),
    ]
