# Generated by Django 6.0.1 on 2026-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('communication', 'Communication'), ('finance', 'Finance'), ('development', 'Development'), ('design', 'Design'), ('security', 'Security'), ('other', 'Other')], max_length=50)),
                ('provider', models.CharField(max_length=150)),
                ('license_count', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('renewal_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
